let D,F=JSON.parse(localStorage.f||"[]"),R=JSON.parse(localStorage.r||"[]");const $=s=>document.querySelector(s),app=$("#app");
async function init(){D=await fetch("data/database.json").then(x=>x.json());$("#fc").textContent=F.length;route()}
function route(){let p=location.hash.slice(1)||"home";document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.getAttribute("href")==="#"+p));$("#crumb").textContent=p.toUpperCase();({home,vehicles,repairs,diagnosis,systems,favorites,recent}[p]||home)()}
function B(){return D.brands.map((b,i)=>`<div class="brand" onclick="brand(${i})"><b>${b[0]}</b><strong>${b[1]}</strong><small>${b[2].length} MODELLE</small></div>`).join("")}
function C(a=D.repairs){return a.map((r,i)=>`<div class="card" onclick="repair(${i})"><div class="ico">${r[3]}</div><span class="pill">${r[2]}</span><h3>${r[1]}</h3><p>${r[6]}</p><div class="meta"><span>◷ ${r[4]}</span><span>${r[5]}</span></div></div>`).join("")}
function home(){app.innerHTML=`<div class="hero"><div class="heroMain"><span class="eyebrow">AUTOMOTIVE KNOWLEDGE SYSTEM</span><h1>Reparaturwissen.<br><em>Präzise. Übersichtlich.</em></h1><p>Fahrzeugdaten, Bauteile, Reparaturen und Diagnosewissen in einer modernen Werkstatt-Wissensbasis.</p><div class="search"><span>⌕</span><input id="hs" placeholder="Bauteil, Reparatur, Fehler oder Fahrzeug …"><kbd>CTRL K</kbd></div></div><div class="heroSide"><div class="ring"><b>2.0</b></div><h3>KFZ MeisterWiki</h3><p>Die Plattform ist für den Ausbau zu einer großen fahrzeugspezifischen Datenbank vorbereitet.</p><div class="metrics"><div class="metric"><b>${D.brands.length}+</b><small>Marken</small></div><div class="metric"><b>${D.repairs.length}</b><small>Guides</small></div><div class="metric"><b>∞</b><small>Ausbau</small></div></div></div></div><div class="title"><div><span class="eyebrow">FAHRZEUGDATENBANK</span><h2>Marke auswählen</h2></div><a href="#vehicles">ALLE MARKEN →</a></div><div class="brands">${B()}</div><div class="title"><div><span class="eyebrow">WERKSTATT-WISSEN</span><h2>Beliebte Reparaturen</h2></div><a href="#repairs">ALLE →</a></div><div class="cards">${C()}</div>`;$("#hs").onclick=()=>openSearch()}
function vehicles(){app.innerHTML=`<div class="pageHead"><div><span class="eyebrow">FAHRZEUGDATENBANK</span><h1>Fahrzeug auswählen</h1><p>Marke → Modell → Motor → Baujahr. So entsteht später die genaue fahrzeugspezifische Anleitung.</p></div><button class="btn primary" onclick="openSearch()">⌕ Suche</button></div><div class="brands">${B()}</div>`}
function brand(i){let b=D.brands[i];R.unshift(["b",i]);R=R.slice(0,8);localStorage.r=JSON.stringify(R);app.innerHTML=`<div class="pageHead"><div><span class="eyebrow">FAHRZEUG / MARKE</span><h1>${b[1]}</h1><p>Modell auswählen.</p></div><button class="btn" onclick="location.hash='vehicles'">← Marken</button></div><div class="panel"><div class="vehicle">${b[2].map(m=>`<div class="select" onclick="model(${i},'${m}')"><small>MODELL</small><strong>${m} →</strong></div>`).join("")}</div></div><div class="title"><div><span class="eyebrow">BELIEBT</span><h2>Reparaturen</h2></div></div><div class="cards">${C(D.repairs.slice(0,4))}</div>`}
function model(i,m){let b=D.brands[i];app.innerHTML=`<div class="pageHead"><div><span class="eyebrow">${b[1].toUpperCase()} / MODELL</span><h1>${m}</h1><p>Für exakte technische Werte muss die konkrete Motorisierung und Generation feststehen.</p></div><button class="btn" onclick="brand(${i})">← ${b[1]}</button></div><div class="panel"><div class="vehicle"><div class="select"><small>MOTOR</small><strong>Auswählen →</strong></div><div class="select"><small>BAUJAHR</small><strong>Auswählen →</strong></div><div class="select"><small>GETRIEBE</small><strong>Auswählen →</strong></div><div class="select"><small>ANTRIEB</small><strong>Auswählen →</strong></div></div></div><div class="safety">⚠ Drehmomente, Füllmengen, Messwerte und Reset-Prozeduren niemals pauschal übernehmen. Erst Fahrzeugvariante eindeutig identifizieren.</div><div class="title"><div><span class="eyebrow">VORBEREITET</span><h2>Typische Reparaturen</h2></div></div><div class="cards">${C()}</div>`}
function repairs(){app.innerHTML=`<div class="pageHead"><div><span class="eyebrow">WERKSTATT-WISSEN</span><h1>Reparaturen</h1><p>Bauteile und Arbeitsbereiche.</p></div></div><div class="tabs">${["Alle","Motor","Bremse","Elektrik","Service","Kühlung"].map((x,i)=>`<button class="tab ${i?"":"on"}" onclick="filter('${x}',this)">${x}</button>`).join("")}</div><div class="cards" id="cl">${C()}</div>`}
function filter(c,e){document.querySelectorAll(".tab").forEach(x=>x.classList.remove("on"));e.classList.add("on");$("#cl").innerHTML=C(c==="Alle"?D.repairs:D.repairs.filter(x=>x[2]===c))}
function diagnosis(){app.innerHTML=`<div class="pageHead"><div><span class="eyebrow">FEHLERFINDUNG</span><h1>Diagnose</h1><p>Vom Symptom zur Ursache – systematisch statt auf Verdacht Teile tauschen.</p></div></div><div class="panel"><h3>Diagnose-Grundablauf</h3><div class="list">${["Fehlerbild exakt beschreiben","Warnleuchten und Fehlerspeicher prüfen","Versorgung und Sicherungen prüfen","Mechanische Ursache ausschließen","Messwerte vergleichen","Reparatur verifizieren"].map((x,i)=>`<div class="row"><div class="ico">${i+1}</div><div><strong>${x}</strong><small>Schritt ${i+1}</small></div></div>`).join("")}</div></div><div class="safety">⚠ Diagnosecodes sind Hinweise, keine automatische Teiletausch-Anweisung. Ursache immer mit Messungen bestätigen.</div>`}
function systems(){app.innerHTML=`<div class="pageHead"><div><span class="eyebrow">FAHRZEUGSYSTEME</span><h1>Baugruppen</h1><p>Die wichtigsten Systeme als Einstieg in die Wissensdatenbank.</p></div></div><div class="cards">${D.systems.map(s=>`<div class="card"><div class="ico">${s[1]}</div><span class="pill">SYSTEM</span><h3>${s[0]}</h3><p>${s[2]}</p></div>`).join("")}</div>`}
function repair(i){let r=D.repairs[i];R.unshift(["r",i]);R=R.slice(0,8);localStorage.r=JSON.stringify(R);$("#detail").innerHTML=`<span class="eyebrow">${r[2].toUpperCase()} / REPARATUR</span><h1>${r[1]}</h1><p class="muted">${r[6]}</p><div class="metrics"><div class="metric"><b>${r[4]}</b><small>Richtwert</small></div><div class="metric"><b>${r[5]}</b><small>Schwierigkeit</small></div><div class="metric"><b>${r[2]}</b><small>System</small></div></div><div class="steps">${["Fahrzeugdaten eindeutig bestimmen: Marke, Modell, Motorisierung und Baujahr.","Werkzeug, Ersatzteil und Sicherheitsmaßnahmen vorbereiten.","Vor dem Ausbau Zustand und Einbaulage dokumentieren.","Bauteil nach fahrzeugspezifischer Anleitung ausbauen.","Neues Teil korrekt einsetzen und Befestigungen kontrollieren.","Funktion prüfen und Warnanzeigen bzw. Fehlerspeicher berücksichtigen."].map((s,n)=>`<div class="step"><div class="stepno">${String(n+1).padStart(2,"0")}</div><div><strong>${s}</strong><p>Fahrzeugspezifische Angaben vor Durchführung prüfen.</p></div></div>`).join("")}</div><div class="safety">⚠ Exakte Drehmomente, Füllmengen, Einstellwerte und Reset-Prozeduren sind abhängig von Fahrzeug, Motor und Baujahr und müssen aus geeigneten technischen Unterlagen stammen.</div><br><button class="btn primary" onclick="fav(${i})">${F.includes(i)?"★ Aus Merkliste":"☆ Zur Merkliste"}</button>`;$("#detailModal").classList.add("open")}
function fav(i){F=F.includes(i)?F.filter(x=>x!==i):[...F,i];localStorage.f=JSON.stringify(F);$("#fc").textContent=F.length;repair(i)}
function favorites(){let a=D.repairs.filter((_,i)=>F.includes(i));app.innerHTML=`<div class="pageHead"><div><span class="eyebrow">WERKZEUGKASTEN</span><h1>Merkliste</h1></div></div>${a.length?`<div class="cards">${C(a)}</div>`:`<div class="empty"><h3>Noch keine gespeicherten Anleitungen</h3><p>Öffne eine Reparatur und füge sie hinzu.</p></div>`}`}
function recent(){let a=R.map(x=>x[0]==="r"?D.repairs[x[1]]:D.brands[x[1]]);app.innerHTML=`<div class="pageHead"><div><span class="eyebrow">WERKZEUGKASTEN</span><h1>Zuletzt geöffnet</h1></div></div><div class="list">${a.map(x=>`<div class="row"><div class="ico">◷</div><strong>${x[1]}</strong></div>`).join("")||`<div class="empty">Noch keine Einträge.</div>`}</div>`}
function openSearch(){let m=$("#searchModal");m.classList.add("open");$("#q").focus();search()};function closeSearch(){$("#searchModal").classList.remove("open")};function closeDetail(){$("#detailModal").classList.remove("open")}
function search(){let q=$("#q").value.toLowerCase(),a=[...D.repairs.map((r,i)=>({t:r[1],s:r[2],f:()=>repair(i)})),...D.brands.map((b,i)=>({t:b[1],s:"Marke",f:()=>brand(i)}))];a=a.filter(x=>(x.t+x.s).toLowerCase().includes(q));$("#results").innerHTML=a.slice(0,12).map((x,i)=>`<div class="result" data-i="${i}"><strong>${x.t}</strong><small>${x.s}</small></div>`).join("")||`<div class="empty">Keine Treffer.</div>`;document.querySelectorAll(".result").forEach((e,i)=>e.onclick=()=>{closeSearch();a[i].f()})}
$("#searchBtn").onclick=openSearch;$("#q").oninput=search;document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openSearch()}if(e.key==="Escape"){closeSearch();closeDetail()}});$("#menu").onclick=()=>$("#side").classList.toggle("open");window.addEventListener("hashchange",route);window.brand=brand;window.model=model;window.repair=repair;window.fav=fav;window.filter=filter;window.openSearch=openSearch;init();